# This file was generated by GoReleaser. DO NOT EDIT.
cask "psi" do
  version "0.0.1-rc.1"

  on_macos do
    on_intel do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_darwin_amd64.tar.gz"
      sha256 "f423b14cc67ad130739a08248d1aa112af5989b0bea64f9c8fdc62c17f0915d6"
    end
    on_arm do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_darwin_arm64.tar.gz"
      sha256 "c7442c595569a0b9183968ccc5f412e9f022c93c834d7266a0ad803c83a43704"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_linux_amd64.tar.gz"
      sha256 "1975dcd8d37c9e6d46ccec2fa382ecb284d93d51b083d0d6db5920217ddf2a68"
    end
    on_arm do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_linux_arm64.tar.gz"
      sha256 "94b2c9be8a85cb7a8b4891eb7bc091671f651ed850211c5c09151e85b00491c3"
    end
  end

  name "psi"
  desc "PostScript interpreter with interactive TUI"
  homepage "https://github.com/ddelvalfraire/postscript-interpreter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "psi"
  binary "psi-engine"

  # No zap stanza required

end
