# This file was generated by GoReleaser. DO NOT EDIT.
cask "psi" do
  version "0.0.1-rc.2"

  on_macos do
    on_intel do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_darwin_amd64.tar.gz"
      sha256 "36396ba24198aae44e54816b83b229fa5fd2d3313256e5b51105b658212b32c6"
    end
    on_arm do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_darwin_arm64.tar.gz"
      sha256 "ce1e8e53db7f5ade8344bfa1a42ceb18fab38c3604f4aea69a00ebaaf5157a75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_linux_amd64.tar.gz"
      sha256 "eb4059c510523db3058bfaa06a1613e6a58cb23b86243a54ed7bd6f1a7666871"
    end
    on_arm do
      url "https://github.com/ddelvalfraire/postscript-interpreter/releases/download/v#{version}/psi_#{version}_linux_arm64.tar.gz"
      sha256 "fb8b3f53951294c655bcee57019ebb72664cbe3d9789b8b9b409798488aca9d7"
    end
  end

  name "psi"
  desc "PostScript interpreter with interactive TUI"
  homepage "https://github.com/ddelvalfraire/postscript-interpreter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "psi"
  binary "psi-engine"

  # No zap stanza required

end
